"""
This type stub file was generated by pyright.
"""

from .autopost import *
from .client import *
from .data import *
from .errors import *
from .http import *
from .types import *
from .types import BotVoteData, GuildVoteData
from .webhook import *

"""
Top.gg Python API Wrapper
~~~~~~~~~~~~~~~~~~~~~~~~~
A basic wrapper for the Top.gg API.
:copyright: (c) 2021 Assanali Mukhanov & Top.gg
:copyright: (c) 2024 null8626 & Top.gg
:license: MIT, see LICENSE for more details.
"""
__title__ = ...
__author__ = ...
__license__ = ...
__version__ = ...
